[package]
name = "vcf2msa"
version = "0.1.0"
authors = ["Max Brown <mb39@sanger.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio="*"
rust-htslib = { version = "0.37.0", default-features = false }